apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 1.1.2.2.2
    title: 1.1.2.2.2 Ensure nodev option set on /dev/shm partition (Automated)
    description: The nodev mount option specifies that the filesystem cannot contain special devices.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(findmnt -kn /dev/shm | grep -v '\''nodev'\'' 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Since the /dev/shm filesystem is not intended to support devices, set this option to
        ensure that users cannot attempt to create special devices in /dev/shm partitions.
    fixGuidance: |-
        - IF - a separate partition exists for /dev/shm.
        Edit the /etc/fstab file and add nodev to the fourth field (mounting options) for the
        /dev/shm partition. See the fstab(5) manual page for more information.
        Example:
        tmpfs /dev/shm tmpfs defaults,rw,nosuid,nodev,noexec,relatime 0 0
        Run the following command to remount /dev/shm with the configured options:
        # mount -o remount /dev/shm
        Note: It is recommended to use tmpfs as the device/filesystem type as /dev/shm is
        used as shared memory space by applications.
