apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 1.1.2.2.4
    title: 1.1.2.2.4 Ensure noexec option set on /dev/shm partition (Automated)
    description: |-
        The noexec mount option specifies that the filesystem cannot contain executable
        binaries.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(findmnt -kn /dev/shm | grep -v '\''noexec'\'' 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Setting this option on a file system prevents users from executing programs from shared
        memory. This deters users from introducing potentially malicious software on the
        system.
    fixGuidance: |-
        - IF - a separate partition exists for /dev/shm.
        Edit the /etc/fstab file and add noexec to the fourth field (mounting options) for the
        /dev/shm partition.
        Example:
        tmpfs /dev/shm tmpfs defaults,rw,nosuid,nodev,noexec,relatime 0 0
        Run the following command to remount /dev/shm with the configured options:
        # mount -o remount /dev/shm
        Note: It is recommended to use tmpfs as the device/filesystem type as /dev/shm is
        used as shared memory space by applications.
