apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 1.3.1.1
    title: 1.3.1.1 Ensure AppArmor is installed (Automated)
    description: AppArmor provides Mandatory Access Controls.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(dpkg-query -s apparmor-utils &>/dev/null && echo "apparmor-utils isinstalled" 2>/dev/null)"
        if [ -n "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Without a Mandatory Access Control system installed only the default Discretionary
        Access Control system will be available.
    fixGuidance: |-
        Install AppArmor.
        # apt install apparmor apparmor-utils
