apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 1.6.4
    title: 1.6.4 Ensure access to /etc/motd is configured (Automated)
    description: |-
        The contents of the /etc/motd file are displayed to users after login and function as a
        message of the day for authenticated users.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'missing=0
        out_0=$([ -e /etc/motd ] && stat -Lc '\''Access: (%#a/%A) Uid: ( %u/ %U) Gid: { %g/ 2>/dev/null)
        if [ -n "$out_0" ]; then
          printf '\''%s'\'' "$out_0" | grep -qF -- "%G)'\'' /etc/motd" || { printf '\''miss-0: %s\n'\'' "%G)'\'' /etc/motd"; missing=$((missing+1)); }
          printf '\''%s'\'' "$out_0" | grep -qF -- "Access: (0644/-rw-r--r--) Uid: ( 0/ root) Gid: ( 0/ root)" || { printf '\''miss-0: %s\n'\'' "Access: (0644/-rw-r--r--) Uid: ( 0/ root) Gid: ( 0/ root)"; missing=$((missing+1)); }
        fi
        if [ "$missing" -eq 0 ]; then printf '\''** PASS **\n'\''; else printf '\''** FAIL **\n'\''; fi'
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        - IF - the /etc/motd file does not have the correct access configured, it could be
        modified by unauthorized users with incorrect or misleading information.
    fixGuidance: |-
        Run the following commands to set mode, owner, and group on /etc/motd:
        # chown root:root $(readlink -e /etc/motd)
        # chmod u-x,go-wx $(readlink -e /etc/motd)
        - OR -
        Run the following command to remove the /etc/motd file:
        # rm /etc/motd
