apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 2.1.13
    title: 2.1.13 Ensure rsync services are not in use (Automated)
    description: |-
        The rsync service can be used to synchronize files between systems over network
        links.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(systemctl is-active rsync.service 2>/dev/null | grep '\''^active'\'' 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        rsync.service presents a security risk as the rsync protocol is unencrypted.
        The rsync package should be removed to reduce the attack area of the system.
        Impact:
        There may be packages that are dependent on the rsync package. If the rsync
        package is removed, these dependent packages will be removed as well. Before
        removing the rsync package, review any dependent packages to determine if they are
        required on the system.
        - IF - a dependent package is required: stop and mask rsync.service leaving the
        rsync package installed.
    fixGuidance: |-
        Run the following commands to stop rsync.service, and remove the rsync package:
        # systemctl stop rsync.service
        # apt purge rsync
        - OR -
        - IF - the rsync package is required as a dependency:
        Run the following commands to stop and mask rsync.service:
        # systemctl stop rsync.service
        # systemctl mask rsync.service
