apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 2.4.1.5
    title: 2.4.1.5 Ensure permissions on /etc/cron.weekly are configured (Automated)
    description: |-
        The /etc/cron.weekly directory contains system cron jobs that need to run on a
        weekly basis. The files in this directory cannot be manipulated by the crontab
        command but are instead edited by system administrators using a text editor. The
        commands below restrict read/write and search access to user and group root,
        preventing regular users from accessing this directory.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(stat -Lc '\''Access: (%a/%A) Uid: ( %u/ %U) Gid: ( %g/ %G)'\'' /etc/cron.weekly/ 2>/dev/null)"
        if [ -n "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Granting write access to this directory for non-privileged users could provide them the
        means for gaining unauthorized elevated privileges. Granting read access to this
        directory could give an unprivileged user insight in how to gain elevated privileges or
        circumvent auditing controls.
    fixGuidance: |-
        - IF - cron is installed on the system:
        Run the following commands to set ownership and permissions on the
        /etc/cron.weekly directory:
        # chown root:root /etc/cron.weekly/
        # chmod og-rwx /etc/cron.weekly/
        Default Value:
        Access: (755/drwxr-xr-x) Uid: ( 0/ root) Gid: ( 0/ root)
