apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 4.2.3
    title: 4.2.3 Ensure ufw service is enabled (Automated)
    description: |-
        UncomplicatedFirewall (ufw) is a frontend for iptables. ufw provides a framework for
        managing netfilter, as well as a command-line and available graphical user interface for
        manipulating the firewall.
        Note:
        • When running ufw enable or starting ufw via its initscript, ufw will flush its chains.
        This is required so ufw can maintain a consistent state, but it may drop existing
        connections (eg ssh). ufw does support adding rules before enabling the firewall.
        • Run the following command before running ufw enable.
        # ufw allow proto tcp from any to any port 22
        • The rules will still be flushed, but the ssh port will be open after enabling the
        firewall. Please note that once ufw is 'enabled', ufw will not flush the chains when
        adding or removing rules (but will when modifying a rule or changing the default
        policy)
        • By default, ufw will prompt when enabling the firewall while running under ssh.
        This can be disabled by using ufw --force enable
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(ufw status 2>/dev/null)"
        if [ -n "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        The ufw service must be enabled and running in order for ufw to protect the system
        Impact:
        Changing firewall settings while connected over network can result in being locked out
        of the system.
    fixGuidance: |-
        Run the following command to unmask the ufw daemon:
        # systemctl unmask ufw.service
        Run the following command to enable and start the ufw daemon:
        # systemctl --now enable ufw.service
        active
        Run the following command to enable ufw:
        # ufw enable
