apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 4.2.2
    title: 4.2.2 Ensure iptables-persistent is not installed with ufw (Automated)
    description: The iptables-persistent is a boot-time loader for netfilter rules, iptables plugin
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(dpkg-query -s iptables-persistent &>/dev/null && echo "iptables-persistentis installed" 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Running both ufw and the services included in the iptables-persistent package may lead
        to conflict
    fixGuidance: |-
        Run the following command to remove the iptables-persistent package:
        # apt purge iptables-persistent
