apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 4.3.1
    title: 4.3.1 Ensure nftables is installed (Automated)
    description: |-
        nftables provides a new in-kernel packet classification framework that is based on a
        network-specific Virtual Machine (VM) and a new nft userspace command line tool.
        nftables reuses the existing Netfilter subsystems such as the existing hook
        infrastructure, the connection tracking system, NAT, userspace queuing and logging
        subsystem.
        Notes:
        • nftables is available in Linux kernel 3.13 and newer
        • Only one firewall utility should be installed and configured
        • Changing firewall settings while connected over the network can result in being
        locked out of the system
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(dpkg-query -s nftables &>/dev/null && echo "nftables is installed" 2>/dev/null)"
        if [ -n "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        nftables is a subsystem of the Linux kernel that can protect against threats originating
        from within a corporate network to include malicious mobile code and poorly configured
        software on a host.
    fixGuidance: |-
        Run the following command to install nftables:
        # apt install nftables
