apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 4.3.2
    title: 4.3.2 Ensure ufw is uninstalled or disabled with nftables (Automated)
    description: |-
        Uncomplicated Firewall (UFW) is a program for managing a netfilter firewall designed to
        be easy to use.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(systemctl is-enabled ufw.service 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Running both the nftables service and ufw may lead to conflict and unexpected
        results.
    fixGuidance: |-
        Run one of the following to either remove ufw or disable ufw and mask ufw.service:
        Run the following command to remove ufw:
        # apt purge ufw
        -OR-
        Run the following commands to disable ufw and mask ufw.service:
        # ufw disable
        # systemctl stop ufw.service
        # systemctl mask ufw.service
        Note: ufw disable needs to be run before systemctl mask ufw.service in order to
        correctly disable UFW
