apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 4.4.1.3
    title: 4.4.1.3 Ensure ufw is not in use with iptables (Automated)
    description: |-
        Uncomplicated Firewall (UFW) is a program for managing a netfilter firewall designed to
        be easy to use.
        • Uses a command-line interface consisting of a small number of simple
        commands
        • Uses iptables for configuration
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(systemctl is-active ufw.service 2>/dev/null | grep '\''^active'\'' 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Running iptables.persistent with ufw enabled may lead to conflict and unexpected
        results.
    fixGuidance: |-
        Run the following command to remove ufw:
        # apt purge ufw
        - OR -
        Run the following commands to disable ufw, and stop and mask ufw.service:
        # ufw disable
        # systemctl stop ufw.service
        # systemctl mask ufw.service
        Note: ufw disable needs to be run before systemctl mask ufw.service in order to
        correctly disable UFW
