apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 4.4.1.2
    title: 4.4.1.2 Ensure nftables is not in use with iptables (Automated)
    description: |-
        nftables is a subsystem of the Linux kernel providing filtering and classification of
        network packets/datagrams/frames and is the successor to iptables.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(systemctl is-active nftables.service 2>/dev/null | grep '\''^active'\'' 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: Running both iptables and nftables may lead to conflict.
    fixGuidance: |-
        Run the following command to remove nftables:
        # apt purge nftables
        - OR -
        Run the following commands to stop and mask nftables.service:
        # systemctl stop nftables.service
        # systemctl mask nftables.service
