apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.1.21
    title: 5.1.21 Ensure sshd PermitUserEnvironment is disabled (Automated)
    description: |-
        The PermitUserEnvironment option allows users to present environment options to
        the SSH daemon.
    severity: high
spec:
    auditCommand: |-
        bash -c 'out="$(sshd -T | grep permituserenvironment 2>/dev/null)"
        val="$(printf '\''%s\n'\'' "$out" | awk '\''{print tolower($NF)}'\'')"
        if [ "$val" = "no" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Permitting users the ability to set environment variables through the SSH daemon could
        potentially allow users to bypass security controls (e.g. setting an execution path that
        has SSH executing trojan'd programs)
    fixGuidance: |-
        Edit the /etc/ssh/sshd_config file to set the PermitUserEnvironment parameter to
        no above any Include entries as follows:
        PermitUserEnvironment no
        Note: First occurrence of an option takes precedence. If Include locations are enabled,
        used, and order of precedence is understood in your environment, the entry may be
        created in a file in Include location.
        Default Value:
        PermitUserEnvironment no
