apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.1.15
    title: 5.1.15 Ensure sshd MACs are configured (Automated)
    description: |-
        This variable limits the types of MAC algorithms that SSH can use during
        communication.
        Notes:
        • Some organizations may have stricter requirements for approved MACs.
        • Ensure that MACs used are in compliance with site policy.
        • The only "strong" MACs currently FIPS 140 approved are:
        o HMAC-SHA1
        o HMAC-SHA2-256
        o HMAC-SHA2-384
        o HMAC-SHA2-512
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(sshd -T | grep -Pi -- '\''macs\h+([^#\n\r]+,)?(hmac-md5|hmac-md5-96|hmac- 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        MD5 and 96-bit MAC algorithms are considered weak and have been shown to increase
        exploitability in SSH downgrade attacks. Weak algorithms continue to have a great deal
        of attention as a weak spot that can be exploited with expanded computing power. An
        attacker that breaks the algorithm could take advantage of a MiTM position to decrypt
        the SSH tunnel and capture credentials and information.
    fixGuidance: |-
        Edit the /etc/ssh/sshd_config file and add/modify the MACs line to contain a comma
        separated list of the site unapproved (weak) MACs preceded with a - above any
        Include entries:
        Example:
        MACs -hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-sha1-96,umac-
        64@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-
        ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,umac-64-
        etm@openssh.com,umac-128-etm@openssh.com
        - IF - CVE-2023-48795 has not been reviewed and addressed, the following etm MACs
        should be added to the exclude list: hmac-sha1-etm@openssh.com,hmac-sha2-256-
        etm@openssh.com,hmac-sha2-512-etm@openssh.com
        Note: First occurrence of an option takes precedence. If Include locations are enabled,
        used, and order of precedence is understood in your environment, the entry may be
        created in a file in Include location.
        Default Value:
        MACs umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-
        etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-
        etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-
        256,hmac-sha2-512,hmac-sha1
