apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.1.22
    title: 5.1.22 Ensure sshd UsePAM is enabled (Automated)
    description: |-
        The UsePAM directive enables the Pluggable Authentication Module (PAM) interface. If
        set to yes this will enable PAM authentication using
        ChallengeResponseAuthentication and PasswordAuthentication directives in
        addition to PAM account and session module processing for all authentication types.
    severity: high
spec:
    auditCommand: |-
        bash -c 'out="$(sshd -T | grep -i usepam 2>/dev/null)"
        val="$(printf '\''%s\n'\'' "$out" | awk '\''{print tolower($NF)}'\'')"
        if [ "$val" = "yes" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        When usePAM is set to yes, PAM runs through account and session types properly. This
        is important if you want to restrict access to services based off of IP, time or other
        factors of the account. Additionally, you can make sure users inherit certain
        environment variables on login or disallow access to the server
    fixGuidance: |-
        Edit the /etc/ssh/sshd_config file to set the UsePAM parameter to yes above any
        Include entries as follows:
        UsePAM yes
        Note: First occurrence of an option takes precedence. If Include locations are enabled,
        used, and order of precedence is understood in your environment, the entry may be
        created in a file in Include location.
        Default Value:
        UsePAM yes
