apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.3.3.2.7
    title: 5.3.3.2.7 Ensure password quality checking is enforced (Automated)
    description: |-
        The pam_pwquality module can be configured to either reject a password if it fails the
        checks, or only print a warning.
        This is configured by setting the enforcing=<N> argument. If nonzero, a password will
        be rejected if it fails the checks, otherwise only a warning message will be provided.
        This setting applies only to the pam_pwquality module and possibly other applications
        that explicitly change their behavior based on it. It does not affect pwmake(1) and
        pwscore(1).
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(grep -PHsi -- '\''^\h*password\h+[^#\n\r]+\h+pam_pwquality\.so\h+([^#\n\r]+\h+)?enforcing=0\b'\'' 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Strong passwords help protect systems from password attacks. Types of password
        attacks include dictionary attacks, which attempt to use common words and phrases,
        and brute force attacks, which try every possible combination of characters. Also
        attackers may try to obtain the account database so they can use tools to discover the
        accounts and passwords.
    fixGuidance: |-
        Run the following command:
        # grep -Pl -- '\bpam_pwquality\.so\h+([^#\n\r]+\h+)?enforcing=0\b'
        /usr/share/pam-configs/*
        Edit any returned files and remove the enforcing=0 argument from the
        pam_pwquality.so line(s)
        Edit /etc/security/pwquality.conf and all files ending in .conf in the
        /etc/security/pwquality.conf.d/ directory and remove or comment out any line
        containing the enforcing = 0 argument:
        Example:
        # sed -ri 's/^\s*enforcing\s*=\s*0/# &/' /etc/security/pwquality.conf
        /etc/security/pwquality.conf.d/*.conf
        Default Value:
        enforcing=1
