apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.3.3.1.1
    title: 5.3.3.1.1 Ensure password failed attempts lockout is configured (Automated)
    description: |-
        The deny=<n> option will deny access if the number of consecutive authentication
        failures for this user during the recent interval exceeds .
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(grep -Pi -- '\''^\h*auth\h+(requisite|required|sufficient)\h+pam_faillock\.so\h+([^#\n\r]+\h+)?deny\h*=\h*(0|[6-9]|[1-9][0-9]+)\b'\'' /etc/pam.d/common-auth 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Locking out user IDs after n unsuccessful consecutive login attempts mitigates brute
        force password attacks against your systems.
    fixGuidance: |-
        Create or edit the following line in /etc/security/faillock.conf setting the deny
        option to 5 or less:
        deny = 5
        Run the following command:
        # grep -Pl -- '\bpam_faillock\.so\h+([^#\n\r]+\h+)?deny\b' /usr/share/pam-
        configs/*
        Edit any returned files and remove the deny=<N> arguments from the
        pam_faillock.so line(s):
        Default Value:
        deny = 3
        Additional Information:
        If a user has been locked out because they have reached the maximum consecutive
        failure count defined by deny= in the pam_faillock.so module, the user can be
        unlocked by issuing the command faillock --user <USERNAME> --reset. This
        command sets the failed count to 0, effectively unlocking the user.
