apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.3.3.2.6
    title: 5.3.3.2.6 Ensure password dictionary check is enabled (Automated)
    description: |-
        The pwquality dictcheck option sets whether to check for the words from the
        cracklib dictionary.
    severity: high
spec:
    auditCommand: |-
        bash -c 'out="$(grep -Psi -- '\''^\h*password\h+(requisite|required|sufficient)\h+pam_pwquality\.so\h+([^#\n\r]+\h+)?dictcheck\h*=\h*0\b'\'' /etc/pam.d/common-password 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        If the operating system allows the user to select passwords based on dictionary words,
        this increases the chances of password compromise by increasing the opportunity for
        successful guesses, and brute-force attacks.
    fixGuidance: |-
        Edit any file ending in .conf in the /etc/security/pwquality.conf.d/ directory
        and/or the file /etc/security/pwquality.conf and comment out or remove any
        instance of dictcheck = 0:
        Example:
        # sed -ri 's/^\s*dictcheck\s*=/# &/' /etc/security/pwquality.conf
        /etc/security/pwquality.conf.d/*.conf
        Run the following command:
        # grep -Pl -- '\bpam_pwquality\.so\h+([^#\n\r]+\h+)?dictcheck\b'
        /usr/share/pam-configs/*
        Edit any returned files and remove the dictcheck argument from the
        pam_pwquality.so line(s)
        Default Value:
        dictcheck = 1
