apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 5.4.3.1
    title: 5.4.3.1 Ensure nologin is not listed in /etc/shells (Automated)
    description: |-
        /etc/shells is a text file which contains the full pathnames of valid login shells. This
        file is consulted by chsh and available to be queried by other programs.
        Be aware that there are programs which consult this file to find out if a user is a normal
        user; for example, FTP daemons traditionally disallow access to users with shells not
        included in this file.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(grep -Ps '\''^\h*([^#\n\r]+)?\/nologin\b'\'' /etc/shells 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        A user can use chsh to change their configured shell.
        If a user has a shell configured that isn't in in /etc/shells, then the system assumes
        that they're somehow restricted. In the case of chsh it means that the user cannot
        change that value.
        Other programs might query that list and apply similar restrictions.
        By putting nologin in /etc/shells, any user that has nologin as its shell is
        considered a full, unrestricted user. This is not the expected behavior for nologin.
    fixGuidance: Edit /etc/shells and remove any lines that include nologin
