apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 6.1.3.1
    title: 6.1.3.1 Ensure rsyslog is installed (Automated)
    description: |-
        The rsyslog software is recommended in environments where journald does not
        meet operation requirements.
    severity: high
spec:
    auditCommand: |-
        bash -c 'out="$(dpkg-query -s rsyslog &>/dev/null && echo "rsyslog is installed" 2>/dev/null)"
        if [ -n "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        The security enhancements of rsyslog such as connection-oriented (i.e. TCP)
        transmission of logs, the option to log to database formats, and the encryption of log
        data en route to a central logging server) justify installing and configuring the package.
    fixGuidance: |-
        Run the following command to install rsyslog:
        # apt install rsyslog
        Default Value:
        Installed
