apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 6.1.2.1.1
    title: 6.1.2.1.1 Ensure systemd-journal-remote is installed (Automated)
    description: |-
        Journald systemd-journal-remote supports the ability to send log events it gathers to
        a remote log host or to receive messages from remote hosts, thus enabling centralized
        log management.
    severity: high
spec:
    auditCommand: |-
        bash -c 'out="$(dpkg-query -s systemd-journal-remote &>/dev/null && echo "systemd-journal-remote is installed" 2>/dev/null)"
        if [ -n "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Storing log data on a remote host protects log integrity from local attacks. If an attacker
        gains root access on the local system, they could tamper with or remove log data that is
        stored on the local system.
        Note: This recommendation only applies if journald is the chosen method for
        client side logging. Do not apply this recommendation if rsyslog is used.
    fixGuidance: |-
        Run the following command to install systemd-journal-remote:
        # apt install systemd-journal-remote
