apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 6.2.4.10
    title: 6.2.4.10 Ensure audit tools group owner is configured (Automated)
    description: |-
        Audit tools include, but are not limited to, vendor-provided and open source audit tools
        needed to successfully view and manipulate audit information system activity and
        records. Audit tools include custom queries and report generators.
    severity: medium
spec:
    auditCommand: |-
        bash -c 'out="$(stat -Lc "%n %G" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace 2>/dev/null)"
        if [ -z "$out" ]; then
          printf '\''%s\n'\'' "** PASS **"
        else
          printf '\''%s\n'\'' "** FAIL **"
        fi
        '
    evaluationRule:
        op: contains
        value: '** PASS **'
    rationale: |-
        Protecting audit information includes identifying and protecting the tools used to view
        and manipulate log data. Protecting audit tools is necessary to prevent unauthorized
        operation on audit information.
    fixGuidance: |-
        Run the following command to change group ownership to the groop root:
        # chgrp root /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace
        /sbin/auditd /sbin/augenrules
