apiVersion: rosshield.io/v1
kind: Check
metadata:
    id: 7.1.10
    title: 7.1.10 Ensure permissions on /etc/security/opasswd are (Automated)
    description: |-
        /etc/security/opasswd and it's backup /etc/security/opasswd.old hold user's
        previous passwords if pam_unix or pam_pwhistory is in use on the system
    severity: medium
spec:
    auditCommand: "true"
    evaluationRule:
        op: contains
        value: <degraded — Phase 2 fixture required>
    rationale: |-
        It is critical to ensure that /etc/security/opasswd is protected from unauthorized
        access. Although it is protected by default, the file permissions could be changed either
        inadvertently or through malicious actions.
    fixGuidance: |-
        Run the following commands to remove excess permissions, set owner, and set group
        on /etc/security/opasswd and /etc/security/opasswd.old is they exist:
        # [ -e "/etc/security/opasswd" ] && chmod u-x,go-rwx /etc/security/opasswd
        # [ -e "/etc/security/opasswd" ] && chown root:root /etc/security/opasswd
        # [ -e "/etc/security/opasswd.old" ] && chmod u-x,go-rwx
        /etc/security/opasswd.old
        # [ -e "/etc/security/opasswd.old" ] && chown root:root
        /etc/security/opasswd.old
        Default Value:
        /etc/security/opasswd Access: (0600/-rw-------) Uid: ( 0/ root) Gid: ( 0/ root)
