/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 only after DB, event bus, and pack index are ready.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Local credential login
         * @description Dual mode (C6):
         *       - `X-Cookie-Auth: true` → refresh token은 응답 본문에서 제외되고
         *         HttpOnly `rosshield_refresh` cookie로 송출 (Web Console).
         *       - 헤더 부재 → 본문에 refresh token 포함 (CLI legacy 호환).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate access token using refresh token
         * @description Dual mode (C6): cookie 우선 → 본문 fallback.
         *       - Web Console (`X-Cookie-Auth: true`) → HttpOnly cookie에서 refresh 추출,
         *         새 refresh를 다시 cookie로 송출(rotation), 본문에는 access만.
         *       - CLI → 본문 `refreshToken` 사용, 본문에 새 refresh 포함.
         *     실패(만료/취소/재사용 탐지)는 모두 401 + cookie clear.
         */
        post: operations["refreshAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke refresh token and clear cookie
         * @description Idempotent. Clears `rosshield_refresh` cookie regardless of token presence.
         *     Cookie 또는 본문 `refreshToken`에서 토큰을 추출해 도메인 layer가 revoke.
         */
        post: operations["logoutAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session info */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current tenant */
        get: operations["getCurrentTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List robots */
        get: operations["listRobots"];
        put?: never;
        /**
         * Register a robot
         * @description Accepts plaintext credentials (memory-only) — domain layer wraps via KEK→DEK.
         *     Response excludes plaintext credentials (Robot meta + credentialId only).
         *     Conflicts (409): duplicate name within fleet, duplicate host:port.
         */
        post: operations["createRobot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robotId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robotId: string;
            };
            cookie?: never;
        };
        /** Get a robot */
        get: operations["getRobot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scan sessions */
        get: operations["listScans"];
        put?: never;
        /**
         * Start a new scan session
         * @description Phase 1 Stage B: inserts session in `pending` state — Orchestrator(scanrun)
         *     start is deferred to a later Stage. `total` is optional (orchestrator computes
         *     it; current Stage accepts external value).
         */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{sessionId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        /**
         * Stream scan progress (WebSocket upgrade)
         * @description WebSocket upgrade endpoint — OpenAPI 3.0/3.1 has no first-class WebSocket
         *     modeling, so this entry is documentation-only. The HTTP GET handler upgrades
         *     the connection (`coder/websocket.Accept`) and pushes JSON frames matching
         *     `ScanProgressMessage` schema (see `components/schemas/ScanProgressMessage`).
         *     See `internal/api/handlers/scan_ws.go` for the wire protocol.
         *
         *     Subscribes to `scan.progress` and `scan.completed` events for the given
         *     sessionId within the caller tenant scope. Emits one `completed` frame
         *     (status=completed/failed/cancelled) and closes.
         *
         *     Auth: Authorization Bearer is required; browser WebSocket API cannot set
         *     custom headers — Phase 1 assumes same-origin. Phase 2 will explore
         *     `?access_token=` query token or session cookie.
         */
        get: operations["streamScanProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reports
         * @description Lists generated reports for the current tenant. PDF body is not included —
         *     only metadata + signature presence flag. Filter by `sessionId` to scope to a
         *     single scan.
         */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}:verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the signature of a report */
        post: operations["verifyReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/license": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * License metadata (E24)
         * @description Returns the active license edition (community|enterprise), expiry, active
         *     features, and quotas. Token and signature are NEVER exposed — only metadata
         *     the operator needs. License unset → community defaults.
         */
        get: operations["getLicenseInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current hash-chain head
         * @description Returns tenant-scoped chain head (Seq + Hash). When no audit entries exist,
         *     returns genesis head (Seq=0, Hash=zero) — Web UI renders "초기 상태".
         */
        get: operations["getAuditHead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a range of the audit chain (external verifier) */
        post: operations["verifyAuditChain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active (non-dismissed) insights */
        get: operations["listInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/{insightId}:dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark an insight as dismissed */
        post: operations["dismissInsight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/{fleetId}/insights:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger insight detectors for a fleet (drift/anomaly/peer)
         * @description Manually runs the insight pipeline for the given fleet. E19 will subscribe
         *     this to scan.completed events for automation; this endpoint remains for
         *     on-demand recompute.
         */
        post: operations["runFleetInsights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List compliance profiles for the current tenant */
        get: operations["listComplianceProfiles"];
        put?: never;
        /** Activate a compliance framework */
        post: operations["createComplianceProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/profiles/{profileId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        /** List snapshots for a profile (created_at DESC) */
        get: operations["listComplianceSnapshots"];
        put?: never;
        /** Generate a snapshot from a scan session */
        post: operations["generateComplianceSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/conversations:ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the advisor a natural-language question (opt-in)
         * @description Starts a new conversation (when conversationId is empty) or appends to an
         *     existing one. The orchestrator runs an LLM/tool dispatch loop and returns
         *     the final answer plus the turns produced in this request.
         *
         *     Returns 503 if the LLM provider is disabled (noop).
         */
        post: operations["askAdvisor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's conversations (updated_at DESC) */
        get: operations["listAdvisorConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        /** Get a conversation with all its turns (sequence ASC) */
        get: operations["getAdvisorConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook endpoints for the current tenant */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /**
         * Register a new webhook endpoint
         * @description Validates URL (absolute http/https), secret (non-empty for HMAC), and event
         *     types (must be in known set: scan.completed, insight.created, audit.checkpoint).
         */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        /** Get a webhook endpoint */
        get: operations["getWebhookEndpoint"];
        /** Update a webhook endpoint (URL · secret · events · format · enabled) */
        put: operations["updateWebhookEndpoint"];
        post?: never;
        /** Delete a webhook endpoint (deliveries are preserved — append-only) */
        delete: operations["deleteWebhookEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{endpointId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List delivery attempts for a webhook endpoint (created_at DESC) */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List automatic backup archives
         * @description Returns .tar.gz archives present in the configured BackupDir (자동 백업
         *     schedule 결과). 빈 디렉터리이거나 BackupDir 미설정이면 빈 배열을 반환합니다.
         */
        get: operations["listBackups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a backup archive
         * @description Streams a single .tar.gz file from BackupDir. Filename은 단순 base name이어야
         *     하며 path traversal(`..`, separator)은 거부됩니다. `.tar.gz` suffix가 강제됩니다.
         *     Range request·Last-Modified는 `http.ServeContent`가 자동 처리합니다.
         */
        get: operations["downloadBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
        };
        Meta: {
            requestId: string;
            serverVersion?: string;
            /** Format: date-time */
            responseAt?: string;
        };
        PageMeta: {
            nextCursor?: string | null;
            prevCursor?: string | null;
            approxTotal?: number;
        };
        Envelope: {
            /** @constant */
            ok: true;
            value?: unknown;
            meta?: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        ErrorCategory: "unauthenticated" | "forbidden" | "not_found" | "conflict" | "validation" | "rate_limited" | "upstream" | "internal";
        Error: {
            /** @description Dotted code (e.g. `robot.not_found`) */
            code: string;
            category: components["schemas"]["ErrorCategory"];
            message: string;
            target?: {
                type?: string;
                id?: string;
            };
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            /** @constant */
            ok: false;
            error: components["schemas"]["Error"];
            meta?: components["schemas"]["Meta"];
        };
        Robot: {
            id: string;
            tenantId: string;
            fleetId: string;
            name: string;
            host: string;
            port: number;
            /** @enum {string} */
            authType: "password" | "privateKey";
            osDistro?: string;
            rosDistro?: string;
            tags?: string[];
            role?: string;
            /** @enum {string} */
            criticality: "low" | "medium" | "high" | "critical";
        };
        ListRobotsResponse: {
            robots: components["schemas"]["Robot"][];
        };
        CreateRobotRequest: {
            fleetId: string;
            name: string;
            host: string;
            /** @description 0 → domain default (22) */
            port?: number;
            /** @enum {string} */
            authType: "password" | "privateKey";
            username: string;
            /** Format: password */
            password?: string;
            privateKeyPem?: string;
            /** Format: password */
            privateKeyPassphrase?: string;
            osDistro?: string;
            rosDistro?: string;
            tags?: string[];
            role?: string;
            /**
             * @description Empty → domain default (medium)
             * @enum {string}
             */
            criticality?: "low" | "medium" | "high" | "critical";
        };
        CreateRobotResponse: {
            robot: components["schemas"]["Robot"];
            credentialId: string;
        };
        StartScanRequest: {
            fleetId: string;
            packId: string;
            /** @description Empty → manual */
            trigger?: string;
            /** @description Optional — orchestrator will compute */
            total?: number;
        };
        ScanSession: {
            sessionId: string;
            tenantId: string;
            fleetId: string;
            packId: string;
            trigger: string;
            status: string;
            total: number;
            completed: number;
            failed: number;
        };
        /**
         * @description Single frame pushed via WebSocket on `/api/v1/scans/{sessionId}/progress`.
         *     kind="progress" → progress payload; kind="completed" → final frame.
         */
        ScanProgressMessage: {
            /** @enum {string} */
            kind: "progress" | "completed";
            /** @description Original EventBus type (e.g. scan.progress) */
            type: string;
            sessionId: string;
            total: number;
            completed: number;
            failed: number;
            /** @description completed/failed/cancelled — only on completed frame */
            status?: string;
            /** @description failed/cancelled reason — only on completed frame */
            reason?: string;
            /** Format: date-time */
            occurredAt: string;
            correlationId?: string;
        };
        AuditHead: {
            tenantId: string;
            /** Format: int64 */
            seq: number;
            /** @description Hash bytes (32B) hex-encoded — 64 chars */
            hashHex: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Report: {
            id: string;
            tenantId: string;
            sessionId: string;
            format: string;
            pdfSha256: string;
            /** Format: int64 */
            pdfSizeBytes: number;
            /** Format: date-time */
            generatedAt: string;
            generatedBy: string;
            signed: boolean;
        };
        ListReportsResponse: {
            reports: components["schemas"]["Report"][];
        };
        Insight: {
            id: string;
            tenantId: string;
            kind: string;
            severity: string;
            robotId?: string;
            fleetId?: string;
            checkId?: string;
            summary: string;
            reasoning?: string;
            rulesApplied?: string[];
            /** Format: double */
            confidence: number;
            producedBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            dismissedAt?: string;
            dismissedBy?: string;
        };
        ListInsightsResponse: {
            insights: components["schemas"]["Insight"][];
        };
        RunInsightsResponse: {
            produced: components["schemas"]["Insight"][];
            count: number;
        };
        ComplianceProfile: {
            id: string;
            tenantId: string;
            framework: string;
            frameworkVersion: string;
            enabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ListComplianceProfilesResponse: {
            profiles: components["schemas"]["ComplianceProfile"][];
        };
        ComplianceControlStatus: {
            controlId: string;
            /** @description pass/fail/partial/not_applicable/unmapped */
            status: string;
            passCount: number;
            failCount: number;
            notes?: string;
        };
        ComplianceSnapshot: {
            id: string;
            tenantId: string;
            profileId: string;
            sessionId?: string;
            /** Format: double */
            overallScore: number;
            passCount: number;
            failCount: number;
            partialCount: number;
            notApplicableCount: number;
            unmappedCount: number;
            /** Format: int64 */
            chainHeadSeq: number;
            chainHeadHash: string;
            statuses?: components["schemas"]["ComplianceControlStatus"][];
            /** Format: date-time */
            createdAt: string;
        };
        ListComplianceSnapshotsResponse: {
            snapshots: components["schemas"]["ComplianceSnapshot"][];
        };
        AdvisorToolCall: {
            id: string;
            toolName: string;
            argsJson?: string;
            resultJson?: string;
            error?: string;
            /** Format: int64 */
            durationMs: number;
        };
        AdvisorTurn: {
            id: string;
            conversationId: string;
            /** @description user/assistant/tool/system */
            role: string;
            content: string;
            sequence: number;
            llmProvider?: string;
            llmModel?: string;
            inputTokens?: number;
            outputTokens?: number;
            /** Format: double */
            costUsd?: number;
            /** Format: date-time */
            createdAt: string;
            toolCalls?: components["schemas"]["AdvisorToolCall"][];
        };
        AdvisorConversation: {
            id: string;
            tenantId: string;
            userId: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdvisorAskResponse: {
            conversationId: string;
            finalAnswer: string;
            turns: components["schemas"]["AdvisorTurn"][];
        };
        ListAdvisorConversationsResponse: {
            conversations: components["schemas"]["AdvisorConversation"][];
        };
        AdvisorConversationDetail: {
            conversation: components["schemas"]["AdvisorConversation"];
            turns: components["schemas"]["AdvisorTurn"][];
        };
        /**
         * @description Domain event type subscribed by the webhook. Empty `events` means all known
         *     events. Add new types only after operator agreement (signed pack).
         * @enum {string}
         */
        WebhookEventType: "scan.completed" | "insight.created" | "audit.checkpoint";
        /**
         * @description Payload serialization format.
         *       - json (default): rosshield raw JSON envelope.
         *       - cef: ArcSight Common Event Format (Splunk OOTB).
         *       - ecs: Elastic Common Schema.
         * @enum {string}
         */
        WebhookFormat: "json" | "cef" | "ecs";
        WebhookEndpoint: {
            id: string;
            tenantId: string;
            /**
             * Format: uri
             * @description Absolute http/https URL
             */
            url: string;
            /**
             * @description Last 4 chars of the HMAC-SHA256 signing secret (`****` if shorter than 4).
             *     Full secret is never returned — operator must manage rotation via the
             *     UPDATE endpoint or external secret manager.
             */
            secretLast4: string;
            /** @description Empty array → subscribes to all known event types. */
            events: components["schemas"]["WebhookEventType"][];
            format: components["schemas"]["WebhookFormat"];
            enabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WebhookEndpointCreate: {
            /** Format: uri */
            url: string;
            /** @description HMAC-SHA256 signing key */
            secret: string;
            events?: components["schemas"]["WebhookEventType"][];
            format?: components["schemas"]["WebhookFormat"];
            /** @default true */
            enabled: boolean;
        };
        /**
         * @description Full replacement — caller must supply current values for fields that should
         *     not change (URL, secret, events, format, enabled).
         */
        WebhookEndpointUpdate: {
            /** Format: uri */
            url: string;
            secret: string;
            events?: components["schemas"]["WebhookEventType"][];
            format?: components["schemas"]["WebhookFormat"];
            enabled?: boolean;
        };
        ListWebhookEndpointsResponse: {
            endpoints: components["schemas"]["WebhookEndpoint"][];
        };
        WebhookDelivery: {
            id: string;
            endpointId: string;
            tenantId: string;
            eventType: components["schemas"]["WebhookEventType"];
            /** @description Source EventBus.Event.ID for cross-reference. */
            eventId: string;
            /** @description Serialized body (CEF/ECS/JSON), base64-encoded. */
            payloadBase64?: string;
            /** @description 0=enqueued, 1..5=actual attempts. */
            attemptCount: number;
            /** Format: date-time */
            lastAttemptedAt?: string;
            /** Format: date-time */
            nextAttemptAt: string;
            succeeded: boolean;
            /** @description HTTP status of last attempt (0 if never attempted). */
            lastResponseStatus: number;
            lastError?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListWebhookDeliveriesResponse: {
            deliveries: components["schemas"]["WebhookDelivery"][];
        };
        BackupMeta: {
            /** @description Base name (no path) */
            filename: string;
            /**
             * Format: int64
             * @description Archive size in bytes
             */
            size: number;
            /** @description Hex digest of the archive */
            sha256: string;
            /**
             * Format: date-time
             * @description RFC3339Nano UTC
             */
            generatedAt: string;
            includesEvidence: boolean;
        };
        BackupListResponse: {
            backups: components["schemas"]["BackupMeta"][];
        };
    };
    responses: {
        /** @description Error envelope */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Limit: number;
        Cursor: string;
        /** @description Field name; prefix with `-` for descending. */
        Sort: string;
        /** @description ULID or UUID. Same key within 24h returns the original response. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["ErrorResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set to `true` to receive refresh token via HttpOnly cookie. */
                "X-Cookie-Auth"?: "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description HttpOnly refresh cookie (only when X-Cookie-Auth is true). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** @description Omitted in cookie mode. */
                        refreshToken?: string;
                        user?: {
                            id?: string;
                            email?: string;
                            displayName?: string;
                            tenantId?: string;
                        };
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    refreshAuth: {
        parameters: {
            query?: never;
            header?: {
                "X-Cookie-Auth"?: "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Legacy mode (CLI). */
                    refreshToken?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description New HttpOnly refresh cookie (cookie mode only). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** @description Omitted in cookie mode. */
                        refreshToken?: string;
                    };
                };
            };
            /** @description Refresh failed (expired/revoked/reuse-detected) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    logoutAuth: {
        parameters: {
            query?: never;
            header?: {
                "X-Cookie-Auth"?: "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refreshToken?: string;
                };
            };
        };
        responses: {
            /** @description No Content (cookie cleared) */
            204: {
                headers: {
                    /** @description Empty/expired refresh cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listRobots: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Field name; prefix with `-` for descending. */
                sort?: components["parameters"]["Sort"];
                fleetId?: string;
                tag?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRobotsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createRobot: {
        parameters: {
            query?: never;
            header?: {
                /** @description ULID or UUID. Same key within 24h returns the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRobotRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRobotResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getRobot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listScans: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                status?: string;
                fleetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: {
                /** @description ULID or UUID. Same key within 24h returns the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartScanRequest"];
            };
        };
        responses: {
            /** @description Created (pending session) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSession"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    streamScanProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket upgrade) */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Event bus not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listReports: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListReportsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    verifyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getLicenseInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        edition?: "community" | "enterprise";
                        issuedTo?: string;
                        /** Format: date-time */
                        issuedAt?: string;
                        /** Format: date-time */
                        expiresAt?: string;
                        expired?: boolean;
                        features?: string[];
                        quotas?: {
                            /** @description 0 = unlimited */
                            robotsMax?: number;
                            /** @description 0 = unlimited */
                            scansPerDay?: number;
                            /** @description 0 = unlimited */
                            llmTokensPerDay?: number;
                        };
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuditHead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditHead"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    from?: string;
                    /** Format: date-time */
                    to?: string;
                };
            };
        };
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listInsights: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                kind?: "drift" | "anomaly" | "peer" | "root_cause" | "prediction";
                severity?: "info" | "low" | "medium" | "high" | "critical";
                robotId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInsightsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    dismissInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insightId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Dismissed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    runFleetInsights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fleetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detectors ran (may produce 0 insights if no history) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInsightsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listComplianceProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListComplianceProfilesResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createComplianceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    framework: "isms-p" | "iso27001-2022" | "nist-800-53-rev5";
                    frameworkVersion: string;
                    /** @default true */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceProfile"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listComplianceSnapshots: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListComplianceSnapshotsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    generateComplianceSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sessionId: string;
                };
            };
        };
        responses: {
            /** @description Generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceSnapshot"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    askAdvisor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Empty → new conversation */
                    conversationId?: string;
                    question: string;
                    maxToolCalls?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorAskResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listAdvisorConversations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdvisorConversationsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdvisorConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorConversationDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWebhookEndpointsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEndpointCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            404: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEndpointUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            404: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWebhookDeliveriesResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listBackups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        value: components["schemas"]["BackupListResponse"];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    downloadBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — binary archive */
            200: {
                headers: {
                    /** @description `attachment; filename="<name>.tar.gz"` */
                    "Content-Disposition"?: string;
                    "Content-Length"?: number;
                    "Last-Modified"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            /** @description Invalid filename (path traversal or wrong suffix) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            /** @description Backup not found or BackupDir unset */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
