/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 only after DB, event bus, and pack index are ready.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Local credential login
         * @description Dual mode (C6):
         *       - `X-Cookie-Auth: true` → refresh token은 응답 본문에서 제외되고
         *         HttpOnly `rosshield_refresh` cookie로 송출 (Web Console).
         *       - 헤더 부재 → 본문에 refresh token 포함 (CLI legacy 호환).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate access token using refresh token
         * @description Dual mode (C6): cookie 우선 → 본문 fallback.
         *       - Web Console (`X-Cookie-Auth: true`) → HttpOnly cookie에서 refresh 추출,
         *         새 refresh를 다시 cookie로 송출(rotation), 본문에는 access만.
         *       - CLI → 본문 `refreshToken` 사용, 본문에 새 refresh 포함.
         *     실패(만료/취소/재사용 탐지)는 모두 401 + cookie clear.
         */
        post: operations["refreshAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke refresh token and clear cookie
         * @description Idempotent. Clears `rosshield_refresh` cookie regardless of token presence.
         *     Cookie 또는 본문 `refreshToken`에서 토큰을 추출해 도메인 layer가 revoke.
         */
        post: operations["logoutAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session info */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current tenant */
        get: operations["getCurrentTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List robots */
        get: operations["listRobots"];
        put?: never;
        /** Register a robot */
        post: operations["createRobot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robotId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robotId: string;
            };
            cookie?: never;
        };
        /** Get a robot */
        get: operations["getRobot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scan sessions */
        get: operations["listScans"];
        put?: never;
        /** Start a new scan session */
        post: operations["createScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}:verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the signature of a report */
        post: operations["verifyReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current hash-chain head */
        get: operations["getAuditHead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a range of the audit chain (external verifier) */
        post: operations["verifyAuditChain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active (non-dismissed) insights */
        get: operations["listInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/{insightId}:dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark an insight as dismissed */
        post: operations["dismissInsight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/{fleetId}/insights:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger insight detectors for a fleet (drift/anomaly/peer)
         * @description Manually runs the insight pipeline for the given fleet. E19 will subscribe
         *     this to scan.completed events for automation; this endpoint remains for
         *     on-demand recompute.
         */
        post: operations["runFleetInsights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List compliance profiles for the current tenant */
        get: operations["listComplianceProfiles"];
        put?: never;
        /** Activate a compliance framework */
        post: operations["createComplianceProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/profiles/{profileId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        /** List snapshots for a profile (created_at DESC) */
        get: operations["listComplianceSnapshots"];
        put?: never;
        /** Generate a snapshot from a scan session */
        post: operations["generateComplianceSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/conversations:ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the advisor a natural-language question (opt-in)
         * @description Starts a new conversation (when conversationId is empty) or appends to an
         *     existing one. The orchestrator runs an LLM/tool dispatch loop and returns
         *     the final answer plus the turns produced in this request.
         *
         *     Returns 503 if the LLM provider is disabled (noop).
         */
        post: operations["askAdvisor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's conversations (updated_at DESC) */
        get: operations["listAdvisorConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        /** Get a conversation with all its turns (sequence ASC) */
        get: operations["getAdvisorConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
        };
        Meta: {
            requestId: string;
            serverVersion?: string;
            /** Format: date-time */
            responseAt?: string;
        };
        PageMeta: {
            nextCursor?: string | null;
            prevCursor?: string | null;
            approxTotal?: number;
        };
        Envelope: {
            /** @constant */
            ok: true;
            value?: unknown;
            meta?: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        ErrorCategory: "unauthenticated" | "forbidden" | "not_found" | "conflict" | "validation" | "rate_limited" | "upstream" | "internal";
        Error: {
            /** @description Dotted code (e.g. `robot.not_found`) */
            code: string;
            category: components["schemas"]["ErrorCategory"];
            message: string;
            target?: {
                type?: string;
                id?: string;
            };
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            /** @constant */
            ok: false;
            error: components["schemas"]["Error"];
            meta?: components["schemas"]["Meta"];
        };
    };
    responses: {
        /** @description Error envelope */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Limit: number;
        Cursor: string;
        /** @description Field name; prefix with `-` for descending. */
        Sort: string;
        /** @description ULID or UUID. Same key within 24h returns the original response. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["ErrorResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set to `true` to receive refresh token via HttpOnly cookie. */
                "X-Cookie-Auth"?: "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description HttpOnly refresh cookie (only when X-Cookie-Auth is true). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** @description Omitted in cookie mode. */
                        refreshToken?: string;
                        user?: {
                            id?: string;
                            email?: string;
                            displayName?: string;
                            tenantId?: string;
                        };
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    refreshAuth: {
        parameters: {
            query?: never;
            header?: {
                "X-Cookie-Auth"?: "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Legacy mode (CLI). */
                    refreshToken?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description New HttpOnly refresh cookie (cookie mode only). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** @description Omitted in cookie mode. */
                        refreshToken?: string;
                    };
                };
            };
            /** @description Refresh failed (expired/revoked/reuse-detected) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    logoutAuth: {
        parameters: {
            query?: never;
            header?: {
                "X-Cookie-Auth"?: "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refreshToken?: string;
                };
            };
        };
        responses: {
            /** @description No Content (cookie cleared) */
            204: {
                headers: {
                    /** @description Empty/expired refresh cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listRobots: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Field name; prefix with `-` for descending. */
                sort?: components["parameters"]["Sort"];
                fleetId?: string;
                tag?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createRobot: {
        parameters: {
            query?: never;
            header?: {
                /** @description ULID or UUID. Same key within 24h returns the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getRobot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listScans: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                status?: string;
                fleetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createScan: {
        parameters: {
            query?: never;
            header?: {
                /** @description ULID or UUID. Same key within 24h returns the original response. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    verifyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuditHead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    from?: string;
                    /** Format: date-time */
                    to?: string;
                };
            };
        };
        responses: {
            /** @description Verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listInsights: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                kind?: "drift" | "anomaly" | "peer" | "root_cause" | "prediction";
                severity?: "info" | "low" | "medium" | "high" | "critical";
                robotId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    dismissInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insightId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Dismissed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    runFleetInsights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fleetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detectors ran (may produce 0 insights if no history) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listComplianceProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createComplianceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    framework: "isms-p" | "iso27001-2022" | "nist-800-53-rev5";
                    frameworkVersion: string;
                    /** @default true */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listComplianceSnapshots: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    generateComplianceSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sessionId: string;
                };
            };
        };
        responses: {
            /** @description Generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    askAdvisor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Empty → new conversation */
                    conversationId?: string;
                    question: string;
                    maxToolCalls?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listAdvisorConversations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdvisorConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
