package main

// admin_seed.go — `rosshield-server seed admin` 서브커맨드 (Phase 1 Exit 데모).
//
// 부팅 직후 system tenant + admin user + 시스템 역할 3개(admin/auditor/operator)를 한 Tx로
// 시드합니다. 사용자가 이 후 로그인 → 로봇 등록 → 스캔 실행 흐름을 시연할 수 있게 만드는
// 진입점입니다. 흐름은 short-lived Bootstrap → tenant.Service.Create → Shutdown 사이클.
//
// 도메인 우회 없이 tenant.Service.Create만 사용해 시드합니다 — Tenant ID는 IDGen 결정값
// (us_*/tn_* prefix). spec의 `--tenant-id` 옵션은 향후 도메인이 명시 ID 시드를 노출하면
// 활성화하기 위한 placeholder로 받기만 하고 현재는 stderr에 한 줄 안내 후 무시합니다.
//
// 중복 시드 거부: tenants 테이블에 row가 하나라도 있으면 거부 (exit 3) — Phase 1의 보수적
// 가정. 멀티 테넌트 시드는 별도 admin API/명령으로 분리.
//
// exit code:
//   0  성공
//   1  bootstrap·storage 오류
//   2  CLI args 또는 validation 오류 (필수 누락/짧은 패스워드/invalid email)
//   3  중복 시드 시도 (이미 tenant·admin이 존재)

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"os"
	"strings"
	"time"

	"github.com/ssabro/rosshield/internal/domain/tenant"
	"github.com/ssabro/rosshield/internal/platform/storage"
)

// seedSubcommand는 `seed ...` 서브커맨드를 처리합니다 (현재는 admin만).
func seedSubcommand(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: rosshield-server seed admin --email <addr> --password <pw> [options]")
		return 2
	}
	switch args[0] {
	case "admin":
		return runSeedAdmin(args[1:])
	case "demo":
		return runSeedDemo(args[1:])
	case "-h", "--help", "help":
		fmt.Fprintln(os.Stderr, `seed 서브커맨드 — system tenant + admin user / 시연 데이터 시드

사용법:
  rosshield-server seed admin --email <addr> --password <pw> [options]
  rosshield-server seed admin --email <addr> --password-stdin [options]
  rosshield-server seed demo  --email <addr> [--data-dir <path>]

admin 옵션:
  --email          관리자 이메일 (필수)
  --password       관리자 패스워드 (필수, ≥12 chars 강제, --password-stdin과 상호 배타)
  --password-stdin stdin에서 패스워드 읽기 (보안 권장 — 명령행 노출 방지)
  --name           tenant 표시 이름 (기본 "Default Tenant")
  --display-name   admin display name (기본 "Administrator")
  --data-dir       데이터 디렉터리 (기본 ~/.rosshield, 부팅 시와 동일)
  --tenant-id      향후 명시 ID 시드용 placeholder (Phase 1에서는 무시 — IDGen이 결정)

demo 옵션 (Phase 2 Exit 시연 데이터 — 멱등):
  --email          시드 대상 tenant의 admin email (필수, 사전에 admin 시드 필요)
  --data-dir       데이터 디렉터리 (기본 ~/.rosshield)

exit code:
  0  성공
  1  bootstrap·storage 오류
  2  CLI args / validation 오류
  3  admin 중복 시드 / demo tenant 미발견`)
		return 0
	default:
		fmt.Fprintf(os.Stderr, "seed: unknown sub-command %q\n", args[0])
		return 2
	}
}

// seedAdminOptions는 `seed admin` CLI 입력 묶음입니다.
type seedAdminOptions struct {
	email         string
	password      string
	passwordStdin bool
	tenantName    string
	displayName   string
	dataDir       string
	tenantID      string // 현재 미사용·placeholder.
}

// seedAdminOutput은 stdout JSON 출력 형식입니다.
type seedAdminOutput struct {
	TenantID   string `json:"tenantId"`
	TenantName string `json:"tenantName"`
	UserID     string `json:"userId"`
	Email      string `json:"email"`
	SeededAt   string `json:"seededAt"`
}

// runSeedAdmin은 `seed admin` 본 흐름입니다.
//
// 처리 순서:
//  1. flag 파싱·필수 옵션 검증 → 실패 시 exit 2.
//  2. 비밀번호를 stdin에서 읽어야 하면 1줄 trim 입력.
//  3. Bootstrap(short-lived) → 중복 시드 사전 거부 → tenant.Service.Create 호출.
//  4. JSON stdout 출력 + Shutdown.
func runSeedAdmin(args []string) int {
	opts, code := parseSeedAdminFlags(args)
	if code != 0 {
		return code
	}
	if code := resolveSeedPassword(&opts); code != 0 {
		return code
	}
	if code := preValidateSeedInput(opts); code != 0 {
		return code
	}
	if opts.tenantID != "" {
		fmt.Fprintln(os.Stderr,
			"seed admin: --tenant-id is currently a placeholder; tenant ID is generated by IDGen.")
	}

	bootCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	platform, err := Bootstrap(bootCtx, Config{
		DataDir: opts.dataDir,
		Logger:  platformLoggerOrDiscard(),
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "seed admin: bootstrap failed: %v\n", err)
		return 1
	}
	defer func() {
		shutdownCtx, c := context.WithTimeout(context.Background(), 10*time.Second)
		defer c()
		_ = platform.Shutdown(shutdownCtx)
	}()

	if exists, err := alreadySeeded(bootCtx, platform); err != nil {
		fmt.Fprintf(os.Stderr, "seed admin: pre-check failed: %v\n", err)
		return 1
	} else if exists {
		fmt.Fprintln(os.Stderr, "seed admin: tenant already exists in this data directory — refusing duplicate seed.")
		return 3
	}

	result, code := executeSeedCreate(bootCtx, platform, opts)
	if code != 0 {
		return code
	}

	out := seedAdminOutput{
		TenantID:   string(result.Tenant.ID),
		TenantName: result.Tenant.Name,
		UserID:     result.Admin.ID,
		Email:      result.Admin.Email,
		SeededAt:   result.Tenant.CreatedAt.UTC().Format(time.RFC3339Nano),
	}
	emitSeedJSON(os.Stdout, out)
	return 0
}

// parseSeedAdminFlags는 flag 파싱 + 필수 옵션 누락 여부 체크입니다.
// 반환 code != 0이면 exit code로 그대로 사용.
func parseSeedAdminFlags(args []string) (seedAdminOptions, int) {
	fs := flag.NewFlagSet("seed admin", flag.ContinueOnError)
	fs.SetOutput(io.Discard) // flag 자체 stderr 메시지 억제 — 우리 메시지 우선.

	var opts seedAdminOptions
	fs.StringVar(&opts.email, "email", "", "관리자 이메일 (필수)")
	fs.StringVar(&opts.password, "password", "", "관리자 패스워드 (≥12 chars)")
	fs.BoolVar(&opts.passwordStdin, "password-stdin", false, "stdin에서 패스워드 읽기")
	fs.StringVar(&opts.tenantName, "name", "Default Tenant", "tenant 표시 이름")
	fs.StringVar(&opts.displayName, "display-name", "Administrator", "admin display name")
	fs.StringVar(&opts.dataDir, "data-dir", defaultDataDir(), "데이터 디렉터리")
	fs.StringVar(&opts.tenantID, "tenant-id", "", "향후 명시 ID 시드 placeholder (현재 무시)")

	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "seed admin: flag parse error: %v\n", err)
		return opts, 2
	}
	return opts, 0
}

// resolveSeedPassword는 --password / --password-stdin 중 하나에서 비밀번호를 채웁니다.
func resolveSeedPassword(opts *seedAdminOptions) int {
	if opts.password != "" && opts.passwordStdin {
		fmt.Fprintln(os.Stderr, "seed admin: --password and --password-stdin are mutually exclusive.")
		return 2
	}
	if opts.passwordStdin {
		reader := bufio.NewReader(os.Stdin)
		line, err := reader.ReadString('\n')
		if err != nil && err != io.EOF {
			fmt.Fprintf(os.Stderr, "seed admin: read stdin password: %v\n", err)
			return 2
		}
		opts.password = strings.TrimRight(line, "\r\n")
	}
	if opts.password == "" {
		fmt.Fprintln(os.Stderr,
			"seed admin: --password or --password-stdin is required.\n  Tip: prefer --password-stdin to avoid leaking via shell history.")
		return 2
	}
	return 0
}

// preValidateSeedInput는 도메인 진입 전 명령행 수준 가드입니다.
// 도메인 validateCreate가 다시 검증하므로 여기서는 누락/길이만 체크 — 형식은 도메인이 결정.
func preValidateSeedInput(opts seedAdminOptions) int {
	if strings.TrimSpace(opts.email) == "" {
		fmt.Fprintln(os.Stderr, "seed admin: --email is required.")
		return 2
	}
	if len(opts.password) < 12 {
		fmt.Fprintln(os.Stderr, "seed admin: --password must be at least 12 characters.")
		return 2
	}
	if strings.TrimSpace(opts.dataDir) == "" {
		fmt.Fprintln(os.Stderr, "seed admin: --data-dir is required.")
		return 2
	}
	return 0
}

// alreadySeeded는 user-tenant(=비-system tenant)가 1개 이상 있는지 검사합니다.
//
// E12 Stage 8 — bootstrap이 cross-tenant 공유 자산용 'system' tenant row를 자동 시드하므로
// SELECT FROM tenants는 항상 ≥1. user-facing tenant 중복 체크는 id != 'system' 필터.
//
// 향후 spec이 멀티 테넌트 시드를 허용하면 (tenant_id, email) 단위 중복 체크로 전환.
func alreadySeeded(ctx context.Context, p *Platform) (bool, error) {
	var exists bool
	err := p.Storage.Bootstrap(ctx, func(ctx context.Context, tx storage.Tx) error {
		row := tx.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM tenants WHERE id != 'system' LIMIT 1)`)
		var n int
		if err := row.Scan(&n); err != nil {
			return err
		}
		exists = n != 0
		return nil
	})
	return exists, err
}

// executeSeedCreate는 tenant.Service.Create를 Bootstrap Tx에서 호출합니다.
//
// 에러 매핑:
//   - validation sentinels(EmptyEmail/InvalidEmail/EmptyPassword/PasswordTooShort) → exit 2
//   - ErrEmailAlreadyExists → exit 3
//   - 그 외 → exit 1
func executeSeedCreate(ctx context.Context, p *Platform, opts seedAdminOptions) (tenant.CreateResult, int) {
	var result tenant.CreateResult
	err := p.Storage.Bootstrap(ctx, func(ctx context.Context, tx storage.Tx) error {
		r, e := p.Tenant.Create(ctx, tx, tenant.CreateRequest{
			Name:             strings.TrimSpace(opts.tenantName),
			Plan:             tenant.PlanDesktopFree,
			AdminEmail:       opts.email,
			AdminPassword:    opts.password,
			AdminDisplayName: opts.displayName,
		})
		if e != nil {
			return e
		}
		result = r
		return nil
	})
	if err != nil {
		switch {
		case errors.Is(err, tenant.ErrEmptyEmail),
			errors.Is(err, tenant.ErrInvalidEmail),
			errors.Is(err, tenant.ErrEmptyPassword),
			errors.Is(err, tenant.ErrPasswordTooShort),
			errors.Is(err, tenant.ErrEmptyName),
			errors.Is(err, tenant.ErrUnknownPlan):
			fmt.Fprintf(os.Stderr, "seed admin: validation: %v\n", err)
			return tenant.CreateResult{}, 2
		case errors.Is(err, tenant.ErrEmailAlreadyExists):
			fmt.Fprintf(os.Stderr, "seed admin: %v\n", err)
			return tenant.CreateResult{}, 3
		default:
			fmt.Fprintf(os.Stderr, "seed admin: create failed: %v\n", err)
			return tenant.CreateResult{}, 1
		}
	}
	return result, 0
}

// emitSeedJSON은 결과를 indented JSON으로 stdout에 씁니다.
func emitSeedJSON(w io.Writer, out seedAdminOutput) {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	_ = enc.Encode(out)
}

// platformLoggerOrDiscard는 시드 명령에서 log 노이즈를 줄이기 위해 stderr로 라우팅합니다.
//
// stdout은 결과 JSON 전용이어야 하므로(파이프 친화), bootstrap 로그는 stderr.
// 레벨은 Warn 이상만 — Bootstrap의 Info("platform bootstrap complete") 노이즈 차단.
func platformLoggerOrDiscard() *slog.Logger {
	return slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelWarn}))
}
